format = """
[ïŸ  ](bold green)$directory(bold blue)$git_branch$git_status[â¯](bold yellow)[â¯](bold purple)[â¯](bold blue) 
"""

right_format = """$all"""

scan_timeout = 60
add_newline = true

# [line_break]
# disabled = true

[directory]
style = "bold blue"

[cmd_duration]
format = "[$duration]($style) "

[status]
disabled = false
format = "[$symbol $status]($style) "
not_found_symbol = "ï€"
not_executable_symbol = "ï‘®"
sigint_symbol = "ï­¦"
map_symbol = true

[git_branch]
format = "[$symbol$branch]($style) "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = "î˜† "

[nodejs]
format = "[$symbol($version )]($style)"

[php]
format = "[$symbol($version )]($style)"
symbol = "î˜ˆ "

[java]
format = "[${symbol}(${version} )]($style)"
symbol = "î‰– "

[rust]
symbol = "î¨ "

[golang]
format = "[$symbol($version )]($style)"
symbol = "ğŸ  "

[package]
format = "[$symbol$version]($style) "
symbol = "ï£– "

